### ISSUE TITLE
怎么手动关闭下拉框呢?

### ISSUE THREAD

**Issue by wyvernnot** [code-artisan/virtual-selector#5]
我在做一个单页面应用, 如果下拉框显示出来的时候跳转到其它页面, 那么下拉框不会消失, 并且一直在那里 >_<

怎么手动关闭呢?

**Comment by code-artisan** [comment]
如果想手动关闭下拉框，可以触发document.的virtual-selector:undropdown事件。这是一个缺陷，没有考虑到SPA的情况。🤗

**Comment by code-artisan** [comment]
@wyvernnot 已修复 https://github.com/code-artisan/selector2/blob/master/src/javascript/VirtualSelector.jsx#L569
