### ISSUE TITLE
表单验证

### ISSUE THREAD

**Issue by wyvernnot** [code-artisan/virtual-selector#7]
能不能加上一个 `required` 属性, 这样可以在必填的字段上应用一个自定义的 `error` 类

**Comment by code-artisan** [comment]
https://github.com/code-artisan/virtual-selector/wiki/%E9%85%8D%E7%BD%AE#nullable  把 `nullable` 置为 `false`，当用户不选择时，默认把第一个选项选中，验证主要还是靠使用者自己去弄。。。关于用验证结果区分状态，可以用`theme`来做，也可以自己传入类名 `className`.
